// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2F17ZDHCLE3umy-0g6gdQ8bO4VaElXnE',
    appId: '1:98838895021:web:713bab9c718b8a22c12924',
    messagingSenderId: '98838895021',
    projectId: 'mygymrapp',
    authDomain: 'mygymrapp.firebaseapp.com',
    storageBucket: 'mygymrapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDo8YeC0KpKxl6LwfePO4NhrYE_qewDc',
    appId: '1:98838895021:android:4dadcd0cf354dd2bc12924',
    messagingSenderId: '98838895021',
    projectId: 'mygymrapp',
    storageBucket: 'mygymrapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs19EKSNycFPnAw9rqpR620W19IHjkklI',
    appId: '1:98838895021:ios:5bc02fe3e4503f56c12924',
    messagingSenderId: '98838895021',
    projectId: 'mygymrapp',
    storageBucket: 'mygymrapp.firebasestorage.app',
    iosClientId: '98838895021-ria2pk7eatf6koh82g0ieagbnkgmilp0.apps.googleusercontent.com',
    iosBundleId: 'com.rafaelbarquero.zarpafit',
  );
}
